profile_image:     FadiSaif-BA.github.io/FadiSaif.jpg
theme: jekyll-theme-minimal
title: Fadi A. Saif Portfolio
show_downloads: True
description: Experienced MEL, Data and Business Analyst, proficient in Process Analysis, Excel, SQL, Python and Tableau with over 10 years of experience in humanitarian and development context.
